sudo: required
branches:
  only:
    - master
    - /201[7-9][0-1][0-9][0-3][0-9]/

services: docker
install: true

env:
  - NODE_VERSION="8.10"

before_install:
- nvm install $NODE_VERSION

language: C

script: ./travis-build.sh
