sudo: required
branches:
  only:
    - master
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/
    - kubernetes-dev

services: docker

language: node_js

node_js: '10'

install: true

script: ./travis-build.sh
